### ISSUE TITLE
re-enable the currently disable ppc tests once qemu is fixed

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/stdarch#1425]
[here](https://gitlab.com/qemu-project/qemu/-/issues/1623) the upstream issue.

**Comment by sayantn** [comment]
The `qemu` issue seems to have been resolved, and the PPC64LE target is all good now, but the PPC64 target still (quite consistently) fails the `vec_lde` tests - but only with `-C target-feature=+vsx`

**Comment by sayantn** [comment]
```
---- core_arch::powerpc::altivec::tests::test_vec_lde_u16 stdout ----
thread 'core_arch::powerpc::altivec::tests::test_vec_lde_u16' panicked at crates/core_arch/src/powerpc/altivec.rs:4802:13:
assertion `left == right` failed
  left: 0
 right: 111
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- core_arch::powerpc::altivec::tests::test_vec_lde_u32 stdout ----
thread 'core_arch::powerpc::altivec::tests::test_vec_lde_u32' panicked at crates/core_arch/src/powerpc/altivec.rs:4811:13:
assertion `left == right` failed
  left: 0
 right: 7303781
```

(with `qemu-ppc64` version `8.2.2` in Ubuntu 24.04, CPU is set to `Power10`
