### ISSUE TITLE
clz fails to produce correct assembly on armv7

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/stdarch#382]
Intrinsics affected are: `_clz_u{8,16,32}`.

```shell
failures:
---- coresimd::arm::v7::assert__clz_u16_clz stdout ----
	disassembly for coresimd::coresimd::arm::v7::assert__clz_u16_clz::_clz_u16_shim: 
	 0: push {fp, lr} 
	 1: mov fp, sp 
	 2: bl fdc8 <_ZN4core3num21_$LT$impl$u20$u16$GT$13leading_zeros17h3c918b237a87689fE> 
	 3: uxth r0, r0 
	 4: pop {fp, pc} 
thread 'coresimd::arm::v7::assert__clz_u16_clz' panicked at 'failed to find instruction `clz` in the disassembly', crates/stdsimd-test/src/lib.rs:370:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
---- coresimd::arm::v7::assert__clz_u32_clz stdout ----
	disassembly for coresimd::coresimd::arm::v7::assert__clz_u32_clz::_clz_u32_shim: 
	 0: b fddc <_ZN4core3num21_$LT$impl$u20$u32$GT$13leading_zeros17h1eadd5618945a0b2E> 
thread 'coresimd::arm::v7::assert__clz_u32_clz' panicked at 'failed to find instruction `clz` in the disassembly', crates/stdsimd-test/src/lib.rs:370:9
---- coresimd::arm::v7::assert__clz_u8_clz stdout ----
	disassembly for coresimd::coresimd::arm::v7::assert__clz_u8_clz::_clz_u8_shim: 
	 0: push {fp, lr} 
	 1: mov fp, sp 
	 2: bl fdb4 <_ZN4core3num20_$LT$impl$u20$u8$GT$13leading_zeros17hdd7115be42dec2f3E> 
	 3: uxtb r0, r0 
	 4: pop {fp, pc} 
thread 'coresimd::arm::v7::assert__clz_u8_clz' panicked at 'failed to find instruction `clz` in the disassembly', crates/stdsimd-test/src/lib.rs:370:9
```

**Comment by sayantn** [comment]
I couldn't even find `_clz_u{8,16,32}`, so I guess this is just very old code, and also this generates the correct asm now
